[package]
name = "keeper-pam-webrtc-rs"
version = "0.2.1"
edition = "2021"

[lib]
name = "keeper_pam_webrtc_rs"
crate-type = ["cdylib"]

[features]
default = ["python"]
python = ["pyo3", "pyo3-log"]
profiling = []

[dependencies]
bytes = "1.10.1"
chrono = "0.4.41"
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter", "json"] }
pyo3 = { version = "0.25.0", features = ["extension-module", "abi3-py37"], optional = true }
pyo3-log = { version = "0.12.4", optional = true }
# Not directly used - included to enforce a minimum version for security (CVE fixes in 0.17.12+)
# Dependency comes through webrtc crate
ring = "0.17.14"
tokio = { version = "1.45.1", features = ["full", "rt-multi-thread"] }
webrtc = "0.13.0"
once_cell = "1.21.3"
anyhow = "1.0.98"
futures = "0.3.31"
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4"] }
base64 = "0.22.1"
reqwest = { version = "0.12.19", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
lazy_static = "1.5.0"
p256 = { version = "0.13.2", features = ["ecdsa"] }
hex = "0.4.3"
sha2 = "0.10.8"
hkdf = "0.12.4"
aes-gcm = "0.10.3"
log = "0.4.27"
smallvec = "1.13.2"
dashmap = "6.1.0"

[package.metadata.maturin]
name = "keeper_pam_webrtc_rs"
python-source = "python"
